name: Hello World Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Echo Hello World
        run: |
            echo "hello pipline"
            mkdir pipeline 
            touch pipeline/output.txt
            touch pipeline/output2.txt
            echo "this is from output1" > pipeline/output.txt
            echo "this is from output2" > pipeline/output2.txt
            pwd 
            ls -la 
            cat pipeline/output2.txt
      - name: upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: output/
            
            
      
